### ISSUE TITLE
你好，下载下来运行pod install 后源码跑不起来。

### ISSUE THREAD

**Issue by csc-EricWu** [yuenov/reader-ios#1]
![image](https://user-images.githubusercontent.com/13517061/84329186-9cb92b80-abb6-11ea-81fc-23e7e558ffa2.png)

**Comment by yuenov** [comment]
@csc-EricWu 请尝试将CocoaPods升级到最新的版本，并重新执行 `pod install`
如果还是报错，请列出完整的报错信息。

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/84499321-f3bd1e80-ace4-11ea-8726-dd8f91264014.png)

**Comment by csc-EricWu** [comment]
cocoapods 已经是最新的了

**Comment by yuenov** [comment]
我从主分支下载最新的代码，并且执行`pod install`后，工程能够正常运行，并没有出现一样的报错信息。这个原因很多，大多数是由于编译参数配置引起的。仅仅根据截图提供的信息并不容易排查到原因。如果你下载代码后并没有对其进行修改，希望你能从网上查找一些可能导致的原因。如果问题解决了，可以在这个`issues`回复解决的办法。

**Comment by csc-EricWu** [comment]
我找到原因了，Podfile 里面不能用 use_frameworks! 我对比后，将它注释下好了。
