### ISSUE TITLE
阅读界面用户体验问题

### ISSUE THREAD

**Issue by zhangBoy** [yuenov/reader-ios#2]
![IMG_1432](https://user-images.githubusercontent.com/13296316/85273101-ba886980-b4af-11ea-9b17-e55542bd735c.jpg)

在阅读界面，文字在右边没有对齐，有方法能做到对齐么？

**Comment by yuenov** [comment]
目前的文字排版无法实现两端对齐。如果自己进行开发建议去掉段落空格然后设置字体属性
``` objc
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
paragraphStyle.alignment = NSTextAlignmentJustified;
```
