### ISSUE TITLE
关于免责声明

### ISSUE THREAD

**Issue by kaich** [yuenov/reader-ios#4]
软件不错，不过有点担心, 这种你服务器提供数据的，非用户自己的行为，这种免不了责吧？

**Comment by yuenov** [comment]
你好：
当用户点击或者搜索时才会触发服务端的搜索行为。小说是实时检索的。

**Comment by kaich** [comment]
我觉得不管你是不是实时检索， 因为是你提供的数据源啊，那就有问题了。 呵呵，拙见， 只是讨论并提醒下而已。

**Comment by yuenov** [comment]
Thanks for your advice
