### ISSUE TITLE
依赖太严重

### ISSUE THREAD

**Issue by xiaoyi3699** [yuenov/reader-ios#5]
能不能把小说阅读部分剔除出来，这样没法用呀

**Comment by yuenov** [comment]
您好，项目是根据接口返回的数据结构进行解析展示的，数据模型也是根据接口返回的数据设计的。所以比较依赖接口数据，并不是一个单机的阅读器。如果个人开发建议使用我们开放的接口，企业开发建议独立修改源码定制。

**Comment by yuenov** [comment]
如果没有其他问题，这个issue先关闭了。
