### ISSUE TITLE
小说内容文本中含有HTML标签的，如何在[RDReadParser paginateWithContent:content ...]计算正确了？

### ISSUE THREAD

**Issue by VictorZhang2014** [yuenov/reader-ios#7]
在`RDReadParser`类的`+(void)paginateWithContent:(NSString *)content charpter:(NSString *)charpter bounds:(CGRect)bounds complete:(void(^)(NSAttributedString *content,NSArray *pages))complete;`是一个非常强的文本解析函数！

经过测试，该函数对应于解析纯文本无HTML标签的非常精确，但是对于文本中带有HTML标签，经过设置HTML解析后，
`NSMutableAttributedString *contentAttr = [[NSMutableAttributedString alloc] initWithData:unicodeContent options:@{NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType} documentAttributes:nil error:nil];`
解析出来的每一页就不太准确

请问大神如何解决这个问题了？

**Comment by VictorZhang2014** [comment]
I've found the solution today, parsing string within HTML elements to a plain text string before parsing the text to  `paginateWithContent` function 

```
var getStringWithoutHTML: String {
        guard let data = self.data(using: .utf8) else {
            return self
        }

        let options: [NSAttributedString.DocumentReadingOptionKey: Any] = [
            .documentType: NSAttributedString.DocumentType.html,
            .characterEncoding: String.Encoding.utf8.rawValue
        ]

        guard let attributedString = try? NSAttributedString(data: data, options: options, documentAttributes: nil) else {
            return self
        }

        return attributedString.string
    }
```
Then it all works

**Comment by yuenov** [comment]
好的，这个问题关掉了

**Comment by VictorZhang2014** [comment]
谢谢作者分享如此好用的代码！！
